name: Lint

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    name: Prettier

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install prettier
      - run: npx prettier --single-quote --check .
